[package]
name = "jlox"
version = "0.1.0"
authors = ["PengTao <tao.peng@eyangmedia.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
slotmap = "1.0"
smol_str = "0.1.17"
strum = { version = "0.20", features = ["derive"] }
strum_macros = "0.20"
